# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: testing with jest

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install libraries
        run: yarn install

      - name: run test suite
        run: yarn test:ci

      - name: upload coverage report to codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          directory: coverage/
          
