# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: testing with jest

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('package.json') }}

      - name: Install libraries
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: run test suite
        run: yarn test --coverage